[package]

name = "phantom"
version = "0.0.3"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
description = "Phantom types for use in other crates."
repostory = "https://github.com/reem/rust-phantom"
license = "MIT"


